# Generated by Django 4.0 on 2022-01-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('learning_type', models.CharField(choices=[('لفظي', 'لفظي'), ('بصري', 'بصري'), ('_', '_')], default=('_', '_'), max_length=50)),
            ],
        ),
    ]
