# Generated by Django 4.0 on 2022-01-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='file_type',
            field=models.CharField(choices=[('text', 'text'), ('video', 'video'), ('sound', 'sound')], default=('text', 'text'), max_length=50),
        ),
    ]
