# Generated by Django 4.0 on 2022-01-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_filesmodel_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
