# Generated by Django 4.0 on 2022-01-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='main',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
